#!/bin/bash
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

printf "${GREEN}Running apt update...${NO_COLOR}\n"
sudo apt update -qq

printf "${GREEN}Running apt upgrade...${NO_COLOR}\n"
sudo apt upgrade -y -qq

printf "${GREEN}Installing packages...${NO_COLOR}\n"
sudo apt install code xclip -y -qq

KEY_BINDINGS_PATH=org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/
UNITY_LAUNCHER_SCHEMA=org.gnome.shell.extensions

gsettings set $KEY_BINDINGS_PATH prev-tab '<Control>q'
gsettings set $KEY_BINDINGS_PATH next-tab '<Control>e'

printf "${GREEN}Moving dock to right position${NO_COLOR}\n"
gsettings set $UNITY_LAUNCHER_SCHEMA.dash-to-dock dock-position LEFT
gsettings set $UNITY_LAUNCHER_SCHEMA.dash-to-dock dock-fixed false

printf "${GREEN}Hiding top bar...${NO_COLOR}\n"
EXTENSIONS_PATH="$HOME/.local/share/gnome-shell/extensions/"
mkdir -p $EXTENSIONS_PATH
cd $EXTENSIONS_PATH
git clone https://github.com/mlutfy/hidetopbar.git hidetopbar@mathieu.bidon.ca

cd hidetopbar@mathieu.bidon.ca
make schemas > /dev/null

gnome-shell-extension-tool -e hidetopbar@mathieu.bidon.ca > /dev/null
gnome-shell --replace & > /dev/null

# Sets up custom aliases
BASH_PATH="$HOME/.bashrc"

if [ -f "$BASH_PATH" ]
then
    FOLDER_NAME=${PWD##*/}
    if ! grep -q "source\s.*$FOLDER_NAME\/aliases" "$BASH_PATH"; then

        echo "source ${PWD}/aliases" >> $BASH_PATH
        exec bash
    else
        echo "${GREEN}Aliases are already loaded.${NO_COLOR}"
    fi
else
    echo "${GREEN}Can't find .bashrc file.${NO_COLOR}"
fi

