#!/bin/bash
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

printf "${GREEN}Running apt update...${NO_COLOR}\n"
sudo apt update -qq

printf "${GREEN}Running apt upgrade...${NO_COLOR}\n"
sudo apt upgrade -y -qq

printf "${GREEN}Installing packages...${NO_COLOR}\n"
sudo apt install code -y -qq

keyBindingsPath=org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/

gsettings set $keyBindingsPath prev-tab '<Control>q'
gsettings set $keyBindingsPath next-tab '<Control>e'
