#!/bin/bash
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

printf "${GREEN}Running apt update...${NO_COLOR}\n"
sudo apt update -qq

printf "${GREEN}Running apt upgrade...${NO_COLOR}\n"
sudo apt upgrade -y -qq

printf "${GREEN}Installing packages...${NO_COLOR}\n"
sudo apt install code -y -qq

keyBindingsPath=org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/
UNITY_LAUNCHER_SCHEMA=org.gnome.shell.extensions

gsettings set $keyBindingsPath prev-tab '<Control>q'
gsettings set $keyBindingsPath next-tab '<Control>e'

printf "${GREEN}Moving dock to right position${NO_COLOR}\n"
gsettings set $UNITY_LAUNCHER_SCHEMA.dash-to-dock dock-position LEFT
gsettings set $UNITY_LAUNCHER_SCHEMA.dash-to-dock dock-fixed false

printf "${GREEN}Hiding top bar...${NO_COLOR}\n"
EXTENSIONS_PATH="$HOME/.local/share/gnome-shell/extensions/"
mkdir -p $EXTENSIONS_PATH
cd $EXTENSIONS_PATH
git clone https://github.com/mlutfy/hidetopbar.git hidetopbar@mathieu.bidon.ca

cd hidetopbar@mathieu.bidon.ca
make schemas > /dev/null

gnome-shell-extension-tool -e hidetopbar@mathieu.bidon.ca > /dev/null
gnome-shell --replace & > /dev/null
